### ISSUE TITLE
Library does not compile for RP2040-based boards due to missing F_CPU

### ISSUE THREAD

**Issue by Daft-Freak** [adafruit/Adafruit_SPIFlash#105]
### Operating System

Linux

### IDE version

1.8.16

### Board

Raspberry Pi Pico

### BSP version

2.4.1

### SPIFlash Library version

3.7.0

### Sketch

```c++
#include <Adafruit_SPIFlash.h>

void setup() {}
void loop() {}
```

### What happened ?

(I'm reporting this for someone else, neither of us is using this library directly, it's getting pulled in through Adafruit_ImageReader)

Compile error:
```
libraries/Adafruit_SPIFlash/src/Adafruit_SPIFlashBase.cpp:202:71: error: 'F_CPU' was not declared in this scope
       (uint32_t)_flash_dev->max_clock_speed_mhz * 1000000U, (uint32_t)F_CPU);
```

Likely because of https://github.com/arduino/ArduinoCore-mbed/issues/221.

### How to reproduce ?

1. Try to compile
2. That's it really

**Comment by hathach** [comment]
thank you for reporting the issue, it is fixed by #107
