### ISSUE TITLE
rp2040 was not declared in this scope

### ISSUE THREAD

**Issue by Piorkos** [adafruit/Adafruit_SPIFlash#118]
### Operating System

MacOS

### IDE version

2.0.0 rc6

### Board

Arduino Nano RP2040 Connect

### BSP version

NA

### SPIFlash Library version

3.10.0

### Sketch as attached file if not stock example

Adafruit_SPIFlash/examples/SdFat_ReadWrite/SdFat_ReadWrite.ino

### What happened ?

When I execute Verify in Arduino IDE I receive such error:

> Adafruit_SPIFlash/src/rp2040/Adafruit_FlashTransport_RP2040.cpp:47:3: error: 'rp2040' was not declared in this scope
>    rp2040.idleOtherCore();

### How to reproduce ?

1. Instal **Arduino Mbed OS Nano boards** by Arduino, version 3.0.1
2. Select Arduino Nano RP2040 Connect board
3. Install **Adafruit_SPIFlash** library (during instalation process permit to install dependency libraries)
4. From the examples open SdFat_ReadWrite.ino
5. Click on **Verify** button
6. Observe errors in output window

**Comment by ladyada** [comment]
this library is only compatible with the philhower core - not mbed core!

**Comment by Piorkos** [comment]
Ok, thanks. I'm new to Arduino, I didn't even know that you can have different cores. Do you maybe know if there is similar library for mbed core?

**Comment by ladyada** [comment]
sorry we do not, we really prefer philhower core - not sure if you can use it tho!
