### ISSUE TITLE
Compatibility issue with Adafruit_ILI0341 and Adafruit_SPIFlash

### ISSUE THREAD

**Issue by anttike** [adafruit/Adafruit_SPIFlash#129]
### Operating System

MacOS

### IDE version

1.8.13

### Board

nRF52840 express

### BSP version

UF2 Bootloader 0.7.0 lib/nrfx (v2.0.0) lib/tinyusb (0.12.0-145-g9775e7691) lib/uf2 (remotes/origin/configupdate-9-gadbb8c7)
Model: Adafruit Feather nRF52840 Express
Board-ID: nRF52840-Feather-revD
Date: Jul 13 2022
SoftDevice: S140 6.1.1

### SPIFlash Library version

Adafruit_BusIO 1.13.2
Adafruit_ILI9341 1.5.12
Adafruit_SPIFlash 4.0.0

### Sketch as attached file if not stock example

#include <Adafruit_ILI9341.h>
#include <Adafruit_SPIFlash.h>

void setup() {
  // put your setup code here, to run once:

}

void loop() {
  // put your main code here, to run repeatedly:

}

### What happened ?

Won't compile. Problem started immediately after I updated SPIFlash to 4.0.0.

### How to reproduce ?

Compile the sketch

### Debug Log as attached txt file

Attached

[Compilelog.txt](https://github.com/adafruit/Adafruit_SPIFlash/files/9813596/Compilelog.txt)

**Comment by hathach** [comment]
- please remove the error message, and upload the full compile log as attached txt file for readability
- Please specify the BSP (nRF52 core) version along with Adafruit_ILI9341, Adafruit_BusIO version. If they are not latest please update all involved libraries

I did an quick test, it seem to run just fine.

**Comment by hathach** [comment]
that is ok, the compiled log include everything. The BSP is the core version, the one when you install/update via Board Manager. your is 1.3.0 which is already latest

```
adafruit/hardware/nrf52/1.3.0/cores/n
```

**Comment by anttike** [comment]
It worked! Million thanks!
