### ISSUE TITLE
How to use it for Seeeduino Xiao nRF52840

### ISSUE THREAD

**Issue by Sladerix** [adafruit/Adafruit_SPIFlash#132]
### Operating System

MacOS

### IDE version

1.8.19

### Board

Seeeduino Xiao nRF52840 Sense

### BSP version

2.7.2 (seeed nRF52 mbed-enabled)

### SPIFlash Library version

4.0.0

### Sketch as attached file if not stock example

examples/SdFat_ReadWrite

### What happened ?

[The board](https://www.seeedstudio.com/Seeed-XIAO-BLE-Sense-nRF52840-p-5253.html) is provided of a on board 2MB QSPI Flash.

While **compiling** I got this errors:

**1.** 
Error while detecting libraries included by 
/var/folders/3h/19k8n4692ln8gwh_2wyqnb0r0000gn/T/arduino_build_382638/sketch/SdFat_ReadWrite.ino.cpp

**2**
In file included from /Users/<username>/Documents/Arduino/libraries/Adafruit_SPIFlash/examples/SdFat_ReadWrite/SdFat_ReadWrite.ino:25:0:
flash_config.h:75:2: error: #error No (Q)SPI flash are defined for your board !
 #error No (Q)SPI flash are defined for your board !
  ^~~~~
  
  
  
  I understand that the board is not yours, the chip is the same btw.. **how can I define the board pin manually?**
  
  
  Thanks in advance

### How to reproduce ?

1. Compile the example "SdFat_ReadWrite"

**Comment by hathach** [comment]
we don't have the hw to help you with, please post this on your board maker. They should be able to provide support for their hardware
