### ISSUE TITLE
DMA option

### ISSUE THREAD

**Issue by joncutting** [adafruit/Adafruit_SPIFlash#133]
### Operating System

Windows 10

### IDE version

VSCode + PlatformIO 6.1.4

### Board

Sparkfun SAMD51 Thing Plus

### BSP version

n/a

### SPIFlash Library version

github latest

### Sketch as attached file if not stock example

n/a

### What happened ?

In Adafruit_FlashTransport_SPI.cpp there is reference to a DMA option. It looks like this was a work in progress but there is no transfer function with that signature so I gather this is dead code. Does anyone here know otherwise?

  // Use SPI DMA if available for best performance
#if defined(ARDUINO_NRF52_ADAFRUIT) && defined(NRF52840_XXAA)
  _spi->transfer(NULL, data, len);
#elif defined(ARDUINO_ARCH_SAMD) && defined(_ADAFRUIT_ZERODMA_H_)
  _spi->transfer(NULL, data, len, true);
#else
  _spi->transfer(data, len);
#endif

### How to reproduce ?

n/a

**Comment by hathach** [comment]
for question please post in the forum support
