### ISSUE TITLE
Adafruit_SPIFlash library not working with Circuit Playground Express

### ISSUE THREAD

**Issue by MrPorcine** [adafruit/Adafruit_SPIFlash#144]
### Operating System

Linux

### IDE version

Arduino 1.8.19

### Board

Circuit Playground Express

### BSP version

Adafruit Circuit Playground Express

### SPIFlash Library version

4.0.0

### Sketch as attached file if not stock example

Stock example "flash_info"

### What happened ?

load "flash_info" example. Compile fails with message "#error No (Q)SPI flash are defined for your board !". 
I see that there was a fix for this some time ago " Fixed for CPX #27 " Oct 2, 2019. Am I missing some #define?

### How to reproduce ?

Above.

**Comment by hathach** [comment]
Just tested, and this indeed occurs when using Arduino one, but compiled fine with Adafruit core. Would you mind switching to use Adafruit core for now, we will try to either
- submit an PR to update define for cplay on Arduino core (will take time for them to merge and release)
- try to fix within the flash example.

**Comment by hathach** [comment]
to use adafruit core, please follow this guide https://learn.adafruit.com/adafruit-arduino-ide-setup/arduino-1-dot-6-x-ide . Basically your need to
- add adafruit json link to IDE preference
- install adafruit samd package
- from IDE menu select "Adafruit SAMD" -> CircuitPlayground Express

Using adafruit package will also enable the use of TinyUSB and other libs from Adafruit ecosystem as well. Let me know if these work for you

![Screenshot 2023-03-10 12:54:32](https://user-images.githubusercontent.com/249515/224235184-ea08121d-7761-4c78-b4f7-eb935ce88757.png)

**Comment by MrPorcine** [comment]
Sorry for the late reply. I found the Arduino library SPIMemory that works with the Circuit Playground and fits my application very well. All I need is readByte, writeByte and eraseSector, so SPIMemory is a simple solution. Once you call the constructor with the select pin used on the CP, 

> SPIFlash flash(33) ;

 all works.

**Comment by hathach** [comment]
no problems, I am glad you find your solution. We will leave this open until we fixed this though. Have fun.
