### ISSUE TITLE
Arduino Nano 33 Sense Compilation Error

### ISSUE THREAD

**Issue by MatthewMong** [adafruit/Adafruit_SPIFlash#146]
### Operating System

Linux

### IDE version

2.0.4

### Board

Arduino Nano 33 BLE Sense

### BSP version

4.0.2

### SPIFlash Library version

4.1.1

### Sketch as attached file if not stock example

examples/flash_info

### What happened ?

Returns compilation error `No (Q)SPI flash are defined for your board`

### How to reproduce ?

Select Arduino Nano 33 BLE as target, compile flash_info or any of the other examples

**Comment by hathach** [comment]
the example cannot define every board variety of SPI/QSPI flash pins. As the error implies, you need to define your own spi/qspi and/or its pin for your nano 33
