### ISSUE TITLE
Incompatible with pico-dvi

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_SPIFlash#148]
### Operating System

Linux

### IDE version

1.8.16

### Board

Adafruit Feather RP2040 DVI

### BSP version

3.2.1

### SPIFlash Library version

4.1.11

### Sketch as attached file if not stock example
```
// 1-bit (black, white) text mode for PicoDVI.

#include <PicoDVI.h>
#include <Adafruit_SPIFlash.h>
#include <Adafruit_TinyUSB.h>

static DVItext1 display(DVI_RES_640x240p60, adafruit_feather_dvi_cfg);

#define USE_DISPLAY (1)
#define USE_FLASH (1)
#define USE_MSC (0)
#define FLASH_FIRST (0)
#define ALLOW_READ (0)
#define ALLOW_WRITE (0)
#define PHASE_DELAY (1000)

#if USE_FLASH
static Adafruit_FlashTransport_RP2040 flashTransport;
static Adafruit_SPIFlash flash(&flashTransport);
#if USE_MSC
static Adafruit_USBD_MSC usb_msc; // USB mass storage object
static bool msc_changed = true; // Is set true on filesystem changes
  
  // FUNCTIONS REQUIRED FOR USB MASS STORAGE ---------------------------------


// Callback on READ10 command.
int32_t msc_read_cb(uint32_t lba, void *buffer, uint32_t bufsize) {
#if ALLOW_READ
  return flash.readBlocks(lba, (uint8_t *)buffer, bufsize / 512) ? bufsize : -1;
#else
  return -1;
#endif
}

// Callback on WRITE10 command.
int32_t msc_write_cb(uint32_t lba, uint8_t *buffer, uint32_t bufsize) {
#if ALLOW_WRITE
  return flash.writeBlocks(lba, buffer, bufsize / 512) ? bufsize : -1;
#else
  return -1;
#endif
}

// Callback on WRITE10 completion.
void msc_flush_cb(void) {
#if ALLOW_WRITE
  flash.syncBlocks();   // Sync with flash
  //SD.cacheClear(); // Clear filesystem cache to force refresh
  msc_changed = true;
#endif
}

#endif
#endif
void setup() { // Runs once on startup
  pinMode(LED_BUILTIN, OUTPUT);
#if FLASH_FIRST
  flash_setup();
  delay(PHASE_DELAY);
  display_setup();
#else
  display_setup();
  delay(PHASE_DELAY);
  flash_setup();
#endif
Serial.println("finished setup");
#if USE_DISPLAY
  display.println("finished setup");
#endif
}

void flash_setup() {
  digitalWrite(LED_BUILTIN, true);
#if USE_FLASH
  if (!flash.begin()) {
    for (;;) digitalWrite(LED_BUILTIN, (millis() / 250) & 1);
  }

#if USE_MSC
  usb_msc.setID("Adafruit", "Internal Flash", "1.0");
  // Set disk size, block size is 512 regardless of spi flash page size
  usb_msc.setCapacity(flash.pageSize() * flash.numPages() / 512, 512);
  usb_msc.setReadWriteCallback(msc_read_cb, msc_write_cb, msc_flush_cb);
  usb_msc.setUnitReady(true); // MSC is ready for read/write
  if (!usb_msc.begin()) {
    pinMode(LED_BUILTIN, OUTPUT);
    for (;;) digitalWrite(LED_BUILTIN, (millis() / 333) & 1);
  }
#endif
#endif
  digitalWrite(LED_BUILTIN, false);
}

void display_setup() {
#if USE_DISPLAY
  if (!display.begin()) { // Blink LED_BUILTIN if insufficient RAM
    for (;;) digitalWrite(LED_BUILTIN, (millis() / 500) & 1);
  }
  display.println("initialized display");
#endif
}

void loop() {
    digitalWrite(LED_BUILTIN, (millis() / 50) & 1);
    #if USE_DISPLAY
    display.printf("%d\r", millis());
    #endif
}
```

### What happened ?

When the flash is initialized, the display stops.

### How to reproduce ?

attach a compatible display to the feather

Upload the sketch

the display will appear for ~1 second, then blank when flash is initialized.

This is just one of several related problems that exists. for instance, if flash is initialized first, then MSC write fails.

PicoDVI does special things on Core 1, and must not be interrupted.

I tried removing the calls to rp2040.idleOtherCore inside rp2040/Adafruit_FlashTransport_RP2040.cpp but this alone did not fully resolve the issue and let me have mass storage + video output

**Comment by jepler** [comment]
After filing this I realized that most likely the DVI generating core *IS* accessing flash: the character generator ROM is declared as an array of `const uint8_t[]` which would mean it's not in RAM. Check if the problem affects a graphical mode differently!

**Comment by hathach** [comment]
@jepler I dive into the code bit, though DVI is too complicated. I think the possible approach here is somehow pause and then resume dvi before and after writing/erase flash or restart the rendering from last known frame buffer ? we can dvi.pause() then resume() before and after the flash.write() and flash.sync()

I have made an PR #149 to skip reading JEDEC which allow flash.begin() to be called freely and flash.read() can be used with pico DVI. However writing still need exclusive flash access.
