### ISSUE TITLE
need a way to hook watchdog feeding

### ISSUE THREAD

**Issue by frank26080115** [adafruit/Adafruit_SPIFlash#152]
I have written firmware that uses the Adafruit nRF52840 Feather Express, and it uses the watchdog timer set to 250ms timeouts. The QSPI flash is used to save and load configuration files, and the user can select from a menu to save/load/new.

I was experiencing almost random crashes and corrupted file systems when using the save feature.

I suspected the watchdog timer. I did a time measurement. The configuration file is about 550 bytes long, and took about 250ms to save.

This explains the crashes and the seemingly randomness of their occurrence. But it also means that even if I call the watchdog feeding from my higher level code, there is still a risk. (I know I can just extend the timeout but I don't want it too long)

I sprinkled watchdog feeding code into `Adafruit_FlashTransport_QSPI_NRF.cpp` and the problem seems to have been resolved. But the way I did it is not so clean, as I manually inserted code into the file specific to the nRF platform. It's not something that is appropriate as a contributed pull-request.

I think it would be nice if the parent classes had a callback installer that can be invoked from the main code. Or some other way, done properly by you guys.

(also it defeats the point of the watchdog timer if the file system itself causes a forever loop, have to be careful here)

**Comment by ladyada** [comment]
hi, there's no way to know what watchdog timing is going to be needed - really the best option is to extend the watchdog timer before doing FS tasks.

if you'd like to submit a PR that is cross-platform and "done properly", for calling a weakly-linked function we would review it for acceptance. thank you! :)
