### ISSUE TITLE
Infinite Loop When Formatting W25Q256JV SPI Chip as FAT

### ISSUE THREAD

**Issue by ysnctr** [adafruit/Adafruit_SPIFlash#155]
### Operating System

MacOS

### IDE version

32768

### Board

Feather NRF52840 Express (Raytac MDBT50Q with Adafruit nrf52840 express bootloader)

### BSP version

Adafruit Feather NRF52840 Express

### SPIFlash Library version

4.2.0

### Sketch as attached file if not stock example

examples/SdFat_format

### What happened ?

I encountered an issue while running my code on different SPI memories, but I'm facing a problem when trying to format the W25Q256JV chip. The issue is that the program gets stuck indefinitely inside the `f_mkfs` function call:

FRESULT r = f_mkfs("", FM_FAT, 0, workbuf, sizeof(workbuf));

It seems that the code may be attempting to format the chip as FAT12, even though the W25Q256JV has a size of 32MB, which is incompatible with FAT12. I tested it with FS_FAT32 instead of FM_FAT, but it did not work again. 

I would appreciate any guidance or solution to resolve this issue. It appears to be related to the file system format not matching the chip's capacity. Please let me know how I can format the chip as FAT32 or if there are any other recommended steps to overcome this problem.

### How to reproduce ?

Run the SdFat_format code with W25Q256JV chip. 

### Debug Log as attached txt file

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
This sketch will ERASE ALL DATA on the flash chip and format it with a new filesystem!
Type OK (all caps) and press enter to continue.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Creating and formatting FAT filesystem (this takes ~60 seconds)...  
(nothing else)

### Screenshots

![image](https://github.com/adafruit/Adafruit_SPIFlash/assets/7975473/85be17b6-2a1b-4994-a4c8-bd1025fb8570)

**Comment by TH1022** [comment]
same issue here

**Comment by hathach** [comment]
where did you buy feather nRF52840 expres  ? the board only comes with 2MB flash

**Comment by ysnctr** [comment]
Hi,

This is a custom board I designed, and it utilizes the Raytac MDBT50Q-1MV2 chip. For firmware updates, I've integrated the Adafruit NRF52840 Express Bootloader. In this design, I've incorporated the W25Q256JV flash memory. Previously, I tested the board with the W25Q128JV_PM, and the library worked as expected. However, I'm currently encountering an issue with the W25Q256JV.

It seems that the example code provided is written for FAT12 formatting, which is not compatible with the larger capacity of the W25Q256JV (32MB). Consequently, I'm unable to format it using the existing code.

If you have any insights or recommendations on how to format the chip as FAT32 or any other steps to overcome this challenge, I would greatly appreciate your assistance.

**Comment by hathach** [comment]
custom board is not supported, we simply don't have the hardware to test/support. PR is welcome, next time, please fill in the correct board info in the issue template.

**Comment by ysnctr** [comment]
I understand that custom boards aren't officially supported, and I appreciate your response. While my board is indeed a custom design, it closely resembles the Adafruit NRF52840 Express. Given this similarity, I'm hoping for guidance on how to format the W25Q256JV chip as FAT32. 

If you can provide any instructions or insights on how to achieve this, it would be greatly appreciated. Thank you for your assistance.
