### ISSUE TITLE
Adding support for IS25LP128 devices

### ISSUE THREAD

**Issue by timthiel** [adafruit/Adafruit_SPIFlash#159]
I am hoping to use this library with a Nano Every board and a IS25LP128 flash (specifically an IS25LP128-JLLA3).

Can someone provide the required entry for the flash_devices.h file.  Alternatively is there a document or information that discusses where to find the required values in a data sheet for the flash?

Are there any additional steps or concerns that need to be addressed?  For instance I found this issue (https://forums.adafruit.com/viewtopic.php?t=201399) which suggests that the Adafruit_SPIFlashBase.cpp file also needs to be modified.

Thanks for any help or advice.

**Comment by hathach** [comment]
those values comes from right flash datasheet. You doin't need modify default list, just passed you own list when called begin().
