### ISSUE TITLE
'g_ADigitalPinMap' was not declared in this scope

### ISSUE THREAD

**Issue by Hsubtnarg** [adafruit/Adafruit_SPIFlash#164]
### Operating System

Windows 11

### IDE version

2.2.1

### Board

Seed XIAO

### BSP version

2.9.2

### SPIFlash Library version

latest

### Sketch as attached file if not stock example

// The MIT License (MIT)
// Copyright (c) 2019 Ha Thach for Adafruit Industries
// Adaptation: Matthieu Charbonnier

#include <SPI.h>
#include "Adafruit_SPIFlash.h"
#include "flash_devices.h"

// Built from the P25Q16H datasheet.
SPIFlash_Device_t const P25Q16H {
  .total_size = (1UL << 21), // 2MiB
  .start_up_time_us = 10000, // Don't know where to find that value
  
  .manufacturer_id = 0x85,
  .memory_type = 0x60,
  .capacity = 0x15,

  .max_clock_speed_mhz = 55,
  .quad_enable_bit_mask = 0x02, // Datasheet p. 27
  .has_sector_protection = 1,   // Datasheet p. 27
  .supports_fast_read = 1,      // Datasheet p. 29
  .supports_qspi = 1,           // Obviously
  .supports_qspi_writes = 1,    // Datasheet p. 41
  .write_status_register_split = 1, // Datasheet p. 28
  .single_status_byte = 0,      // 2 bytes
  .is_fram = 0,                 // Flash Memory
};

// Use this constructor to tune the QSPI pins.
Adafruit_FlashTransport_QSPI flashTransport(P0_21, P0_25, P0_20, P0_24, P0_22, P0_23);
// Adafruit_FlashTransport_QSPI flashTransport;

Adafruit_SPIFlash flash(&flashTransport);

#define BUFSIZE   4096

#define TEST_WHOLE_CHIP 1

#ifdef LED_BUILTIN
  uint8_t led_pin = LED_BUILTIN;
#else
  uint8_t led_pin = 0;
#endif

// 4 byte aligned buffer has best result with nRF QSPI
uint8_t bufwrite[BUFSIZE] __attribute__ ((aligned(4)));
uint8_t bufread[BUFSIZE] __attribute__ ((aligned(4)));

// the setup function runs once when you press reset or power the board
void setup()
{
  Serial.begin(115200);
  while ( !Serial ) delay(100);   // wait for native usb

  flash.begin(&P25Q16H, 1);

  pinMode(led_pin, OUTPUT);
  flash.setIndicator(led_pin, false);

  Serial.println("Adafruit Serial Flash Speed Test example");
  Serial.print("JEDEC ID: "); Serial.println(flash.getJEDECID(), HEX);
  Serial.print("Flash size: "); Serial.println(flash.size());
  Serial.flush();

  write_and_compare(0xAA);
  write_and_compare(0x55);

  Serial.println("Speed test is completed.");
  Serial.flush();
}

void print_speed(const char* text, uint32_t count, uint32_t ms)
{
  Serial.print(text);
  Serial.print(count);
  Serial.print(" bytes in ");
  Serial.print(ms / 1000.0F, 2);
  Serial.println(" seconds.");

  Serial.print("Speed: ");
  Serial.print( (count / 1000.0F) / (ms / 1000.0F), 2);
  Serial.println(" KB/s.\r\n");
}

bool write_and_compare(uint8_t pattern)
{
  uint32_t ms;

  Serial.println("Erase chip");
  Serial.flush();

#if TEST_WHOLE_CHIP
  uint32_t const flash_sz = flash.size();
  flash.eraseChip();
#else
  uint32_t const flash_sz = 4096;
  flash.eraseSector(0);
#endif

  flash.waitUntilReady();

  // write all
  memset(bufwrite, (int) pattern, sizeof(bufwrite));
  Serial.print("Write flash with 0x");
  Serial.println(pattern, HEX);
  Serial.flush();
  ms = millis();

  for(uint32_t addr = 0; addr < flash_sz; addr += sizeof(bufwrite))
  {
    flash.writeBuffer(addr, bufwrite, sizeof(bufwrite));
  }

  uint32_t ms_write = millis() - ms;
  print_speed("Write ", flash_sz, ms_write);
  Serial.flush();

  // read and compare
  Serial.println("Read flash and compare");
  Serial.flush();
  uint32_t ms_read = 0;
  for(uint32_t addr = 0; addr < flash_sz; addr += sizeof(bufread))
  {
    memset(bufread, 0, sizeof(bufread));

    ms = millis();
    flash.readBuffer(addr, bufread, sizeof(bufread));
    ms_read += millis() - ms;

    if ( memcmp(bufwrite, bufread, BUFSIZE) )
    {
      Serial.print("Error: flash contents mismatched at address 0x");
      Serial.println(addr, HEX);
      for(uint32_t i=0; i<sizeof(bufread); i++)
      {
        if ( i != 0 ) Serial.print(' ');
        if ( (i%16 == 0) )
        {
          Serial.println();
          if ( i < 0x100 ) Serial.print('0');
          if ( i < 0x010 ) Serial.print('0');
          Serial.print(i, HEX);
          Serial.print(": ");
        }

        if (bufread[i] < 0x10) Serial.print('0');
        Serial.print(bufread[i], HEX);
      }

      Serial.println();
      return false;
    }
  }

  print_speed("Read  ", flash_sz, ms_read);
  Serial.flush();

  return true;
}

void loop()
{
  // nothing to do
}

### What happened ?

Would not compile, gave error 

```
c:\Users\grant\OneDrive\Documents\Arduino\libraries\Adafruit_SPIFlash\src\qspi\Adafruit_FlashTransport_QSPI_NRF.cpp: In member function 'virtual void Adafruit_FlashTransport_QSPI::begin()':
c:\Users\grant\OneDrive\Documents\Arduino\libraries\Adafruit_SPIFlash\src\qspi\Adafruit_FlashTransport_QSPI_NRF.cpp:53:35: error: 'g_ADigitalPinMap' was not declared in this scope
.sck_pin = (uint8_t)g_ADigitalPinMap[_sck],
^~~~~~~~~~~~~~~~
```

### How to reproduce ?

I fixed it by modifying Adafruit_FlashTransport_QSPI_NRF to this

```
void Adafruit_FlashTransport_QSPI::begin(void) {
  // Init QSPI flash
  nrfx_qspi_config_t qspi_cfg = {
      .xip_offset = 0,
      .pins =
          {
              .sck_pin = (uint8_t)_sck,
              .csn_pin = (uint8_t)_cs,
              .io0_pin = (uint8_t)_io0,
              .io1_pin = (uint8_t)_io1,
              .io2_pin = (uint8_t)_io2,
              .io3_pin = (uint8_t)_io3,
          },
      .prot_if = {.readoc = NRF_QSPI_READOC_READ4O, // 0x6B read command
                  .writeoc = NRF_QSPI_WRITEOC_PP4O, // 0x32 write command
                  .addrmode = NRF_QSPI_ADDRMODE_24BIT,
                  .dpmconfig = false},
      .phy_if =
          {
              .sck_delay = 10,
              .dpmen = false,
              .spi_mode = NRF_QSPI_MODE_0,
              .sck_freq = NRF_QSPI_FREQ_32MDIV16, // start with low 2 Mhz speed
          },
      .irq_priority = 7};

  // No callback for blocking API
  nrfx_qspi_init(&qspi_cfg, NULL, NULL);
}
```
not sure why it needed g_ADigitalPinMap

**Comment by hathach** [comment]
- long sketch must be attached as txt file
- for 3rd party boards, contact their maker for your support
