### ISSUE TITLE
read8, read16, and read32 don't work

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_SPIFlash#17]
The `read8()`, `read16()`, and `read32()` convenience routines don't work because they are testing the return value from `readBuffer()` incorrectly. For example:
```cpp
uint8_t Adafruit_SPIFlash::read8(uint32_t addr)
{
	uint8_t ret;
	return readBuffer(addr, &ret, sizeof(ret)) ? 0xff : ret;
}
```
`readBuffer()` returns a count of bytes read, which will be interpreted as `true` if  != 0, so this will return `0xff`.

**Comment by hathach** [comment]
:man_facepalming: :man_facepalming:
