### ISSUE TITLE
using Adafruit_SPIFlash without cache

### ISSUE THREAD

**Issue by sykoraj** [adafruit/Adafruit_SPIFlash#178]
Using SPIFlash without cache to save RAM (4kB)

Could the SPIFlash library be safely used without cache? Of course keeping in mind the impact on performance. But in practice, any real usage waits at the end for syncDevice() anyway. Particularly on some Arduinos, saving 4kB makes sense.

There appears to be a brute force solution to overwrite source at:
Adafruit_SPIFlash::Adafruit_SPIFlash() : Adafruit_SPIFlashBase() {
  _cache_en = false; // -> originally was: true;
  _cache = NULL;
}

Is it safe? could that be an instance init option, configurable argument?

It is worth noting, that my intended cache-less usage scenario is for direct readSector() writeSector() low-level usage, not using full FAT implementation of upper layers.

**Comment by sykoraj** [comment]
following on the above:
there seems to be a config option Adafruit_SPIFlash::Adafruit_SPIFlash(Adafruit_FlashTransport *transport, bool useCache)
and later inside the code is mentioned that on __AVR__ platform, the cache can be switched off.

Is it save on other platforms as well?

**Comment by hathach** [comment]
you can also use the Adafruit_SPIFlashBase.h
