### ISSUE TITLE
Latest commit breaks fatfs_circuitpython.ino

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_SPIFlash#2]
c6e7292 breaks the `fatfs_circuitpython.ino` example in some way. See https://forums.adafruit.com/viewtopic.php?f=57&t=127244. (I confirmed the problem.)

```
Adafruit M0 Express CircuitPython Flash Example
Flash chip JEDEC ID: 0x1401501
readBuffer failed!
f_mount failed with error code: 13
Failed to mount filesystem!
Was CircuitPython loaded on the board first to create the filesystem?
```

**Comment by ladyada** [comment]
should be fixed now, was a return error error!

**Comment by ladyada** [comment]
@dhalbert i dont watch all repos (and theres 950 so i dont know which im missing) - when bugs come up plz assign or @ me :)

**Comment by dhalbert** [comment]
@ladyada will do!
