### ISSUE TITLE
SPIFlash not working on Circuit Playground Express

### ISSUE THREAD

**Issue by makermelissa** [adafruit/Adafruit_SPIFlash#26]
The flash.begin() function is not working on the Circuit Playground Express. It works fine on a Feather M0, so I don't think it's the SAMD21 chip.

**Comment by ladyada** [comment]
its probably due to SPI/SPI1 mixup
this is the correct definition
https://github.com/adafruit/Adafruit_Arcada/blob/master/Adafruit_Arcada_CircuitPlaygroundExpress.h#L21

**Comment by makermelissa** [comment]
Thanks for a good starting point. I'll try using that.

**Comment by makermelissa** [comment]
Ok, got it! A fix will be coming shortly. Also need to fix it in ImageLoader.
