### ISSUE TITLE
GetJEDECID() broken

### ISSUE THREAD

**Issue by manitou48** [adafruit/Adafruit_SPIFlash#4]
In Adafruit_SPIFlash.cpp,  getJEDECID() does not return proper values.  FIX: get rid of 3 dummy writes.

**Update**: My initial tests were with an 8MB W25Q64FV SPI flash, and getJEDECID() failed with the the 3 dummy spiwrite's, and the data sheet did not indicate dummy write's were required.  Having received my Express, I see that getJEDECID() works with or without the 3 dummy writes.

**Comment by dhalbert** [comment]
@manitou48 should we close this?

**Comment by manitou48** [comment]
On Tue, Jul 31, 2018 at 12:28:06PM -0700, Dan Halbert wrote:
> @manitou48 should we close this?
> 
> -- 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/adafruit/Adafruit_SPIFlash/issues/4#issuecomment-409339653

as you see fit.  the datasheet says you don't need dummy reads.

-- 
  Tom Dunigan  thdunigan@gmail.com   http://tnlandforms.us

**Comment by ladyada** [comment]
closing cause it seems...resolved? if not, please submit a PR and we'll test :)
