### ISSUE TITLE
writeBuffer works sometimes?

### ISSUE THREAD

**Issue by infinitemind2** [adafruit/Adafruit_SPIFlash#52]
Been investigating using the flash memory on the IstyBitsy M4 to store some persistent data over resets.
So started with the flash_manipulator.ino code and modified to only use page 0 (for now).
Firstly succeeded in writing some data, great.
Then went to change it, no luck, using the same code.
Found that if I erase the chip before writing to the flash, the data on the flash is altered by the change invoked by writeBuffer otherwise the data remains unchanged.

output from setup

Adafruit Serial Flash Manipulator example
JEDEC ID: C84015
Flash size: 2097152
Page size: 256
Number of pages: 8192

Modified code is in attached file
[TestFlashManipulator.ino.txt](https://github.com/adafruit/Adafruit_SPIFlash/files/4484493/TestFlashManipulator.ino.txt)

**Comment by ladyada** [comment]
you have to erase a page before writing it, FLASH memory can only overwrite 0xFF data
