### ISSUE TITLE
Library does not work with Feather M0 Express With No Bootloader 

### ISSUE THREAD

**Issue by redknight106** [adafruit/Adafruit_SPIFlash#62]
I currently have two Feather M0 Express boards both running without a Boot-Loader as I am programming and debugging via SWD.

1)Original Feather: Uses standard fitted memory.
2)Modified Feather: Original fitted memory removed to use not supported Flash Memory AT25XV041B.

I selected no boot-loader by changing the boards.txt file: 
Was: adafruit_feather_m0_express.build.ldscript=linker_scripts/gcc/flash_with_bootloader.ld
Now: adafruit_feather_m0_express.build.ldscript=linker_scripts/gcc/flash_without_bootloader.ld

Having the No Boot-loader option enabled a can run all I2C code and SPI display code like the adafruit ST7735 library with no issues. As I have no USB connected I am using the Serial1 Hardware UART which is connected to my Digital Discovery Logic Analyser.

When using the example 'flash_info' program I return no results for either 'JEDEC ID:' or 'FLASH Size:' They are both blank. This is on the Original Feather.

When trying the same code on the Modified Feather I get the same blank results.

I did enter the AT25XV041B Flash into the 'flash_devices.h' file as shown below:

`#define AT25XV041B                                                                                       \
  {                                                                                                                         \
    .total_size = (1 << 22), /* 4 MiB */                                                                  \
        .start_up_time_us = 10000, .manufacturer_id = 0x1f,                                  \
    .memory_type = 0x44, .capacity = 0x01, .max_clock_speed_mhz = 85,          \
    .quad_enable_bit_mask = 0x00, .has_sector_protection = true,                      \
    .supports_fast_read = true, .supports_qspi = true,                                          \
    .supports_qspi_writes = false, .write_status_register_split = false,                   \
    .single_status_byte = false,                                                                               \
  }` 

I used my Digital Discovery Logic Analyser to spy in the SPI lines and noted that the SPI was reading the Flash chip and returning the following:
`Data: h9F | h00, hFF | h1F, hFF | h44, hFF | h02,`

This data output matches the datasheet but for some reason the 'JEDEC ID:' or 'FLASH Size:' They are both blank when looking at the serial out. Have I missed something?

I'm surprised that a Original Feather with no Boot-loader would return blank data as it uses the supported SPI Flash Data. Is there a way to get this library to work without a Boot-loader? 

Thank you.

**Comment by hathach** [comment]
I don't think the bootloader is the factor to make the library failed to work. It probably mess-up with other things related to bootloader. The result is simply the side effect of it and not the bug of this library. To get help on this project, you should open an topic on our support forum, there is more people could help you there.

PS: next time opening the bug report, please fill out all the question, those are not optional.
