### ISSUE TITLE
Creating file using PIC24FJ on W25Q32JV

### ISSUE THREAD

**Issue by vijayprakash1** [adafruit/Adafruit_SPIFlash#68]
Hello All,
Can I use this library for storing CSV, pdf files in W25Q32JV using the PIC32MM0256 microcontroller?

**Comment by ladyada** [comment]
if it supports Arduino, yes

**Comment by vijayprakash1** [comment]
No Doesn't support Arduino.

Is there any other sample code or ways to implement same on non-arduino MCU

**Comment by ladyada** [comment]
no
