### ISSUE TITLE
Having trouble editing the flash_devices.h to add a new flash memory.

### ISSUE THREAD

**Issue by callmeraffiq** [adafruit/Adafruit_SPIFlash#81]
As stated above I have a problem in editing the flash_devices.h file in the library to add a new device that are not listed in this library. Can anybody help me and verify whether what I have edited is correct? and is it possible to add another flash memory excluding the listed one?

//This is the Edited part for new flash device Winbond W25Q512JV
//Datasheet:"https://www.winbond.com/resource-files/W25Q512JV%20SPI%20RevB%2006252019%20KMS.pdf"

#define W25Q512JV                                                               
  {                                                                            
    .total_size = (1 << 26), /* 64 MiB */                                       
    .start_up_time_us = 5000, .manufacturer_id = 0xef,                     
    .memory_type = 0x40, .capacity = 0x20, .max_clock_speed_mhz = 133,         
    .quad_enable_bit_mask = 0x01, .has_sector_protection = false,              
    .supports_fast_read = true, .supports_qspi = true,                        
    .supports_qspi_writes = true, .write_status_register_split = false,      
  }

**Comment by hathach** [comment]
as issue template suggests, for questions and how-to please post it in our forum support where there are more people to help you out.
