### ISSUE TITLE
Error on formatting SPI flash

### ISSUE THREAD

**Issue by igortomiatti** [adafruit/Adafruit_SPIFlash#98]
Hi,

I'm using a W25Q64 external flash on ESP32.

The following problem occurs when trying to format the flash:

`Adafruit SPI Flash FatFs Format Example
Flash chip JEDEC ID: 0xEF4017
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
This sketch will ERASE ALL DATA on the flash chip and format it with a new filesystem!
Type OK (all caps) and press enter to continue.
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
Creating and formatting FAT filesystem (this takes ~60 seconds)...
Error, f_mount failed with error code: 13`

Another person had the same problem, as: #58

**Comment by hathach** [comment]
Please fill out all the filed in the bug template in your first post, then post an extra comment to let me know. Otherwise this issue will be closed.
